export const CURRENCIES_SIGN: Array<{
  optionName: string;
  value: string;
  isDefault?: boolean;
}> = [
  { optionName: 'Philippine Peso (₱)', value: 'PHP' },
  { optionName: 'United States Dollar ($)', value: 'USD' },
  { optionName: 'Euro (€)', value: 'EUR' },
  { optionName: 'Japanese Yen (¥)', value: 'JPY' },
  { optionName: 'British Pound Sterling (£)', value: 'GBP' },
  { optionName: 'Australian Dollar ($)', value: 'AUD' },
  { optionName: 'Canadian Dollar ($)', value: 'CAD' },
  { optionName: 'Swiss Franc (CHF)', value: 'CHF' },
  { optionName: 'Chinese Yuan Renminbi (¥)', value: 'CNY' },
  { optionName: 'Hong Kong Dollar ($)', value: 'HKD' },
  { optionName: 'New Zealand Dollar ($)', value: 'NZD' },
  { optionName: 'Swedish Krona (kr)', value: 'SEK' },
  { optionName: 'South Korean Won (₩)', value: 'KRW' },
  { optionName: 'Singapore Dollar ($)', value: 'SGD' },
  { optionName: 'Norwegian Krone (kr)', value: 'NOK' },
  { optionName: 'Mexican Peso ($)', value: 'MXN' },
  { optionName: 'Indian Rupee (₹)', value: 'INR' },
  { optionName: 'Brazilian Real (R$)', value: 'BRL' },
  { optionName: 'Russian Ruble (₽)', value: 'RUB' },
  { optionName: 'South African Rand (R)', value: 'ZAR' },
  { optionName: 'Argentine Peso ($)', value: 'ARS' },
  { optionName: 'Bahraini Dinar (.د.ب)', value: 'BHD' },
  { optionName: 'Bangladeshi Taka (৳)', value: 'BDT' },
  { optionName: 'Bulgarian Lev (лв)', value: 'BGN' },
  { optionName: 'Chilean Peso ($)', value: 'CLP' },
  { optionName: 'Colombian Peso ($)', value: 'COP' },
  { optionName: 'Costa Rican Colón (₡)', value: 'CRC' },
  { optionName: 'Czech Koruna (Kč)', value: 'CZK' },
  { optionName: 'Danish Krone (kr)', value: 'DKK' },
  { optionName: 'Egyptian Pound (£)', value: 'EGP' },
  { optionName: 'Fijian Dollar ($)', value: 'FJD' },
  { optionName: 'Ghanaian Cedi (¢)', value: 'GHS' },
  { optionName: 'Hungarian Forint (Ft)', value: 'HUF' },
  { optionName: 'Icelandic Króna (kr)', value: 'ISK' },
  { optionName: 'Indonesian Rupiah (Rp)', value: 'IDR' },
  { optionName: 'Israeli Shekel (₪)', value: 'ILS' },
  { optionName: 'Kenyan Shilling (KSh)', value: 'KES' },
  { optionName: 'Kuwaiti Dinar (د.ك)', value: 'KWD' },
  { optionName: 'Malaysian Ringgit (RM)', value: 'MYR' },
  { optionName: 'Nigerian Naira (₦)', value: 'NGN' },
  { optionName: 'Peruvian Sol (S/.)', value: 'PEN' },
  { optionName: 'Polish Złoty (zł)', value: 'PLN' },
  { optionName: 'Qatari Riyal (﷼)', value: 'QAR' },
  { optionName: 'Romanian Leu (lei)', value: 'RON' },
  { optionName: 'Saudi Riyal (﷼)', value: 'SAR' },
  { optionName: 'Thai Baht (฿)', value: 'THB' },
  { optionName: 'Turkish Lira (₺)', value: 'TRY' },
  { optionName: 'Ukrainian Hryvnia (₴)', value: 'UAH' },
  { optionName: 'Vietnamese Đồng (₫)', value: 'VND' },
];

export default CURRENCIES_SIGN;
